@echo off
echo [1;37;44m
PATH c:\;c:\brief;c:\system;c:\msc;c:\msc\bin;c:\utility;c:\norton;c:\windows;c:\decnet
set INCLUDE=c:\msc\include
set LIB=c:\msc\lib;h:\newpcip\lib
set MASM=/T/Z/B63
set TMP=g:
set TEMP=g:
@echo on
