tcp.obj: tcp.c
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl /Ze tcp.c
	lib ..\..\lib\tcp-+tcp;

tcp_dump.obj: tcp_dump.c
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl tcp_dump.c
	lib ..\..\lib\tcp-+tcp_dump;
