log.obj: log.c ..\..\include\udp.h ..\..\include\custom.h ..\..\include\sockets.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl log.c
	lib ..\..\lib\udp-+log;

res_name.obj: res_name.c ..\..\include\udp.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl res_name.c
	lib ..\..\lib\udp-+res_name;

udp_init.obj: udp_init.c ..\..\include\udp.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl udp_init.c
	lib ..\..\lib\udp-+udp_init;

udp_name.obj: udp_name.c ..\..\include\udp.h ..\..\include\custom.h ..\..\include\sockets.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl udp_name.c
	lib ..\..\lib\udp-+udp_name;

udp_time.obj: udp_time.c ..\..\include\udp.h ..\..\include\custom.h ..\..\include\sockets.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl udp_time.c
	lib ..\..\lib\udp-+udp_time;

udp_allo.obj: udp_allo.c ..\..\include\udp.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl udp_allo.c
	lib ..\..\lib\udp-+udp_allo;

udp_sock.obj: udp_sock.c ..\..\include\udp.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl udp_sock.c
	lib ..\..\lib\udp-+udp_sock;

udp_writ.obj: udp_writ.c ..\..\include\udp.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl udp_writ.c
	lib ..\..\lib\udp-+udp_writ;

udp_send.obj: udp_send.c ..\..\include\udp.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl udp_send.c
	lib ..\..\lib\udp-+udp_send;

udpdemux.obj: udpdemux.c ..\..\include\udp.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl udpdemux.c
	lib ..\..\lib\udp-+udpdemux;

udpswap.obj: udpswap.c ..\..\include\udp.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl udpswap.c
	lib ..\..\lib\udp-+udpswap;

udptable.obj: udptable.c ..\..\include\udp.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl udptable.c
	lib ..\..\lib\udp-+udptable;

udp_clos.obj: udp_clos.c ..\..\include\udp.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl udp_clos.c
	lib ..\..\lib\udp-+udp_clos;

udp_open.obj: udp_open.c ..\..\include\udp.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl udp_open.c
	lib ..\..\lib\udp-+udp_open;

udp_boot.obj: udp_boot.c ..\..\include\bootp.h
	cl /c /DDEBUG /DCOMPAT42 /Gs /I..\..\include /Zd /Zl udp_boot.c
	lib ..\..\lib\udp-+udp_boot;
