chirp.obj: chirp.asm
	masm /ml chirp;
	lib ..\..\lib\pc-+chirp;

crit_err.obj: crit_err.asm
	masm /ml crit_err;
	lib ..\..\lib\pc-+crit_err;

crock.obj: crock.asm
	masm /ml crock;
	lib ..\..\lib\pc-+crock;

cursor_t.obj: cursor_t.asm
	masm /ml cursor_t;
	lib ..\..\lib\pc-+cursor_t;

dma.obj: dma.asm
	masm /ml dma;
	lib ..\..\lib\pc-+dma;

dosl.obj: dosl.asm
	masm /ml dosl;
	lib ..\..\lib\pc-+dosl;

ffirst.obj: ffirst.asm
	masm /ml ffirst;
	lib ..\..\lib\pc-+ffirst;

gencpy.obj: gencpy.asm
	masm /ml gencpy;
	lib ..\..\lib\pc-+gencpy;

int.obj: int.asm
	masm /ml int;
	lib ..\..\lib\pc-+int;

io.obj: io.asm
	masm /ml io;
	lib ..\..\lib\pc-+io;

mach_typ.obj: mach_typ.asm
	masm /ml mach_typ;
	lib ..\..\lib\pc-+mach_typ;

mkraw.obj: mkraw.asm
	masm /ml mkraw;
	lib ..\..\lib\pc-+mkraw;

seg.obj: seg.asm
	masm /ml seg;
	lib ..\..\lib\pc-+seg;

_prints.obj: _prints.c
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl _prints.c
	lib ..\..\lib\pc-+_prints;

getopt.obj: getopt.c
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl getopt.c
	lib ..\..\lib\pc-+getopt;

q.obj: q.c
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl q.c
	lib ..\..\lib\pc-+q;

signal.obj: signal.c
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl signal.c
	lib ..\..\lib\pc-+signal;

version.obj: version.c
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl version.c
	lib ..\..\lib\pc-+version;

cuexit.obj: cuexit.c
	cl /c /DDEBUG /DMSC40 /Gs /I..\..\include /Zd /Zl cuexit.c
	lib ..\..\lib\pc-+cuexit;

pcip_ope.obj: pcip_ope.c
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl pcip_ope.c
	lib ..\..\lib\pc-+pcip_ope;
