ggp.obj: ggp.c ..\..\include\ip.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl ggp.c
	lib ..\..\lib\ip-+ggp;

icmp.obj: icmp.c ..\..\include\ip.h ..\..\include\icmp.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl icmp.c
	lib ..\..\lib\ip-+icmp;

in_alloc.obj: in_alloc.c ..\..\include\ip.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl in_alloc.c
	lib ..\..\lib\ip-+in_alloc;

in_dump.obj: in_dump.c ..\..\include\ip.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl in_dump.c
	lib ..\..\lib\ip-+in_dump;

in_init.obj: in_init.c ..\..\include\ip.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl in_init.c
	lib ..\..\lib\ip-+in_init;

in_more.obj: in_more.c ..\..\include\ip.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl in_more.c
	lib ..\..\lib\ip-+in_more;

in_mymac.obj: in_mymac.c ..\..\include\ip.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl in_mymac.c
	lib ..\..\lib\ip-+in_mymac;

in_open.obj: in_open.c ..\..\include\ip.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl in_open.c
	lib ..\..\lib\ip-+in_open;

in_write.obj: in_write.c ..\..\include\ip.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl in_write.c
	lib ..\..\lib\ip-+in_write;

indemux.obj: indemux.c ..\..\include\ip.h ipconn.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl indemux.c
	lib ..\..\lib\ip-+indemux;

inroute.obj: inroute.c ..\..\include\ip.h ..\..\include\custom.h redirtab.h
	cl /c /DDEBUG /DMSC /Gs /I..\..\include /Zd /Zl inroute.c
	lib ..\..\lib\ip-+inroute;
